"""
GLT LAUNCH - the first nine posts, hand-curated then published automatically.

A new profile is judged as a grid, not as a feed, so these nine are chosen rather
than sampled: they alternate photography and colour tiles, introduce the brand
before selling anything, and cover every design family and price point.
Everything after this is generated by batch.py.
"""
import csv, os
from glt_studio import Studio, PRODUCT_LED
from scene_studio import scene_post
from copy_bank import HASHTAGS

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "launch")
os.makedirs(OUT, exist_ok=True)
S = Studio(palette=PRODUCT_LED)

# (n, kind, sku, scene_or_template, dominant, headline, accent, body, caption)
NINE = [
 (1, "tile", "glt-tote-martini-caesar-fries", "statement", "berry",
  "Gifts for women who don't take life too seriously",
  "well, hello", "GIRLS LOVE THINGS · new here",
  "New here. We make funny, sweary, cocktail-loving homeware and gifts — the sort of thing you buy for the friend who makes you laugh most.\n\nStart with a martini. Everything else follows."),
 (2, "scene", "glt-tote-martini-caesar-fries", "entryway", None,
  "Girl dinner, but make it a handbag", "a crumb of dignity", "Cotton tote · £22.55",
  "Carries: keys, phone, lip balm, and the full emotional weight of a martini, a caesar and some chips.\n\nPrinted both sides. Lime, orange or white."),
 (3, "scene", "glt-mug-sweary-animal-print", "kitchen-counter", None,
  "Monday has a message for you", "well, hello", "11oz & 15oz · from £10.35",
  "Some mugs say live laugh love. This one has a different idea.\n\nCeramic, dishwasher safe, absolutely not for the office Christmas swap."),
 (4, "scene", "glt-print-girl-dinner-martini", "gallery-wall", None,
  "Three olives is a food group", "if you know, you know", "Framed print · from £20.92",
  "Giclée print in a mountboard window frame, two sizes.\n\nFor the bar cart, the kitchen nook, or the wall you keep meaning to sort out."),
 (5, "tile", "glt-mug-sweary-animal-print", "statement", "olive",
  "Nobody has ever asked for a smaller martini",
  "a crumb of dignity", "no notes",
  "Just putting that out there.\n\n(Everything we make is at the link in bio, but honestly this one's free.)"),
 (6, "scene", "glt-tee-girl-dinner", "bed-flatlay", None,
  "Dinner is a martini and three chips", "treat yourself, it's Friday", "Organic tee · from £30.32",
  "A full nutritional breakdown, printed on organic combed cotton. 2XS to 5XL.\n\nWear it to dinner. Order accordingly."),
 (7, "scene", "glt-print-lime-leopard-love-you-bye", "kitchen-wall", None,
  "Love you bye", "the whole conversation", "Framed print · from £16.85",
  "The most-used phrase in this house, in lime leopard print.\n\n11x14 or 16x20, framed and ready to hang."),
 (8, "tile", "glt-tee-boxy-neon-fuck-this-shit", "hero", "pink",
  "Some days need a bigger font", "said with your whole chest", "Organic boxy tee · £28.62",
  "Neon green on organic cotton, cropped and boxy.\n\nAn outfit and a warning in one. XS to 5XL."),
 (9, "scene", "glt-sticker-girl-lunch-martini", "neutral-flatlay", None,
  "Everything from £2.89", "go on then", "Stickers to framed prints · £2.89–£48",
  "Stickers at £2.89. Mugs at £10.35. Framed prints, totes, tees, party invites.\n\nWhole shop at the link in bio — start small, we don't mind."),
]

SIZES = {1:"feed",2:"feed",3:"feed",4:"feed",5:"feed",6:"feed",7:"feed",8:"feed",9:"feed"}
ROT = {6:-2.5, 9:4.0}

rows = []
for n, kind, sku, tgt, dom, hl, ac, bd, cap in NINE:
    name = f"{n:02d}_{kind}_{sku.replace('glt-','')}.jpg"
    path = os.path.join(OUT, name)
    if kind == "scene":
        scene_post(sku, tgt, path, size=SIZES[n], headline=hl, accent=ac,
                   body=bd, rotate=ROT.get(n, 0))
    else:
        S.render(tgt, sku=sku, size=SIZES[n], dominant=dom,
                 headline=hl, accent=ac, body=bd, out=path)
    tags = HASHTAGS["default"] if n in (1, 5, 9) else (
challenge := HASHTAGS["apparel"] if "tee" in sku or "tote" in sku else HASHTAGS["print"])
    rows.append({"order": n, "file": name, "type": kind,
                 "on_image": hl, "caption": f"{cap}", "hashtags": tags,
                 "approved": ""})

with open(os.path.join(OUT, "launch-schedule.csv"), "w", newline="") as f:
    w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
    w.writeheader(); w.writerows(rows)
print(f"{len(rows)} launch posts -> {OUT}")
